# Generated by Django 2.2.24 on 2023-01-10 17:30

from django.db import migrations

def definition_new_buildings(apps, schema_editor):
    advertisements = apps.get_model('property', 'Flat')
    for advertisement in advertisements.objects.all():
        if advertisement.construction_year >= 2015:
            advertisement.new_building = True
        elif advertisement.construction_year < 2015:
            advertisement.new_building = False
        else:
            advertisement.new_building = None
        advertisement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230109_2205'),
    ]

    operations = [
        migrations.RunPython(definition_new_buildings),
    ]
