# Generated by Django 2.2.24 on 2023-01-13 17:33

from django.db import migrations
import phonenumbers


def parse_phone_numbers(apps, schema_editor):
    advertisements = apps.get_model('property', 'Flat')
    for advertisement in advertisements.objects.all():
        advertisement.owner_pure_phone = phonenumbers.parse(
            advertisement.owners_phonenumber, 'RU')
        advertisement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230113_1956'),
    ]

    operations = [
        migrations.RunPython(parse_phone_numbers),
    ]
