# Generated by Django 2.2.24 on 2023-01-14 06:23

from django.db import migrations


def copy_flat_to_owner(apps, schema_editor):
    advertisements = apps.get_model('property', 'Flat')
    owner = apps.get_model('property', 'Owner')
    for advertisement in advertisements.objects.all():
        owner.objects.get_or_create(full_name=advertisement.owner,
                                    phonenumber=advertisement.owners_phonenumber,
                                    pure_phone=advertisement.owner_pure_phone)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owner),
    ]
